# Generated by Django 4.2.7 on 2023-12-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactModel',
            fields=[
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
                ('boolean_field', models.BooleanField()),
                ('char_field', models.CharField(max_length=255)),
                ('date_field', models.DateField()),
                ('date_time_field', models.DateTimeField()),
                ('email_field', models.EmailField(max_length=254)),
                ('integer_field', models.IntegerField()),
                ('text_field', models.TextField()),
                ('time_field', models.TimeField()),
            ],
        ),
    ]
